[package]
name = "demo-hack-impl"
version = "0.1.0"
authors = ["Nika Layzell <nika@thelayzells.com>"]
edition = "2018"

publish = false

[lib]
proc-macro = true

[dependencies]
absolution-hack = { path = ".." }
absolution = { path = "../.." }
quote = "1.0"
