name: Tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Test
      run: cargo test
    - name: Test example
      run: cd examples/string-enum && cargo run --example simple
    - name: Test absolution-hack
      run: cd absolution-hack/example && cargo run

